# Language Detection

---

**Dataset:**
- [papluca/language-identification](https://huggingface.co/datasets/papluca/language-identification)

### Import used libraries

In [1]:
import pandas as pd

pd.set_option("display.max_rows", 500)
pd.set_option("display.max_colwidth", 500)

### Load Dataset

In [2]:
from datasets import load_dataset

dataset = load_dataset("papluca/language-identification")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

train.csv:   0%|          | 0.00/12.0M [00:00<?, ?B/s]

valid.csv: 0.00B [00:00, ?B/s]

test.csv: 0.00B [00:00, ?B/s]

Generating train split:   0%|          | 0/70000 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/10000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/10000 [00:00<?, ? examples/s]

In [3]:
print(dataset)

DatasetDict({
    train: Dataset({
        features: ['labels', 'text'],
        num_rows: 70000
    })
    validation: Dataset({
        features: ['labels', 'text'],
        num_rows: 10000
    })
    test: Dataset({
        features: ['labels', 'text'],
        num_rows: 10000
    })
})

In [4]:
train_df = dataset["train"].to_pandas()
val_df   = dataset["validation"].to_pandas()
test_df  = dataset["test"].to_pandas()

print("Num classes:", train_df["labels"].nunique())

Num classes: 20

In [5]:
train_df.head(10)

,labels,text
0,pt,"os chefes de defesa da estónia, letónia, lituânia, alemanha, itália, espanha e eslováquia assinarão o acordo para fornecer pessoal e financiamento para o centro."
1,bg,размерът на хоризонталната мрежа може да бъде по реда на няколко километра ( km ) за на симулация до около 100 km за на симулация .
2,zh,很好，以前从不去评价，不知道浪费了多少积分，现在知道积分可以换钱，就要好好评价了，后来我就把这段话复制走了，既能赚积分，还省事，走到哪复制到哪，最重要的是，不用认真的评论了，不用想还差多少字，直接发出就可以了，推荐给大家！！
3,th,สำหรับ ของเก่า ที่ จริงจัง ลอง honeychurch ของเก่า ที่ ไม่ 29 สำหรับ เฟอร์นิเจอร์ และ เงิน ไท ร้อง บริษัท ที่ 122 สำหรับ ลาย คราม
4,ru,Он увеличил давление .
5,pl,"S Jak sobie życzysz: Widzisz, jak Hitler zabija Żydów?"
6,ur,اس کے بارے میں ، سفید شادی کی شرح کے بعد سفید اورنمایاں طور پر سفید اورنمایاں طور پر .
7,sw,"Zabuni ya ushindani pia imekuwa rahisi kwa sifa ya kurudi kwenye mapendekezo yake ya grant , na dudovitz hivi karibuni ilikuwa kulea kwa ajili ya kuendeleza nyenzo za matangazo ya slick na kushiriki fedha kwa mipango nyingine ya mapendeleo ya umma kwa juhudi za shirikishi za afya , utetezi wa sera , homelessness , nyumbani msaada wa vurugu , msaada wa kibinafsi na maendeleo ya teknolojia ."
8,tr,"Devasa 12 yüzyıl abbatiale saint-Pierre-Et-Saint-Paul , Aziz Peter ' ın 17 yüzyılda Roma ' da tamamlama kadar Hıristiyan ' en büyük kilisesi idi ."
9,ur,موجودہ اثاثوں میں سے ایک کا اضافہ ہو سکتا ہے ۔

In [6]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   labels  70000 non-null  object
 1   text    70000 non-null  object
dtypes: object(2)
memory usage: 1.1+ MB

### EDA on training data

#### Check for NaNs

In [7]:
print("Null values:")
print(train_df.isnull().sum())

Null values:
labels    0
text      0
dtype: int64

#### Check for duplicates

In [8]:
print("Number of duplicate rows:", train_df.duplicated().sum())

Number of duplicate rows: 1020

In [9]:
duplicate_rows = train_df[train_df.duplicated(keep=False)].sort_values("text")
duplicate_rows.head(20)

,labels,text
13778,ar,- ولدى المجلس حاليا مشروع نشط لمعالجة معايير الموارد الطبيعية .
28542,ar,- ولدى المجلس حاليا مشروع نشط لمعالجة معايير الموارد الطبيعية .
44424,hi,1822 में शहर की अंग ् रेजी कॉलोनी के वित ् त-पोषण के लिए निवासियों और आगंतुकों की एक तरह की सैर की गई है .
24676,hi,1822 में शहर की अंग ् रेजी कॉलोनी के वित ् त-पोषण के लिए निवासियों और आगंतुकों की एक तरह की सैर की गई है .
1686,tr,"2001 ' in ikinci yarısında 183,000 ' den fazla kişinin görev yaptığını belirttiler ."
32904,tr,"2001 ' in ikinci yarısında 183,000 ' den fazla kişinin görev yaptığını belirttiler ."
8775,nl,"49 doden, 148 gewonden bij gewelddadige aanvallen in Irak..."
35261,nl,"49 doden, 148 gewonden bij gewelddadige aanvallen in Irak..."
35372,it,"49 morti, 148 feriti in violenti attacchi in Iraq"
40619,it,"49 morti, 148 feriti in violenti attacchi in Iraq"
65861,pt,"49 mortos, 148 feridos em ataques violentos no Iraque"
44401,pt,"49 mortos, 148 feridos em ataques violentos no Iraque"
66361,pl,"49 zabitych, 148 rannych w brutalnych atakach w Iraku"
19480,pl,"49 zabitych, 148 rannych w brutalnych atakach w Iraku"
11256,pt,A mulher apanhou o canguru.
5252,pt,A mulher apanhou o canguru.
15714,nl,"Adem in, adem uit, ga verder."
22263,nl,"Adem in, adem uit, ga verder."
66799,tr,"Aksi takdirde , oteller manzaralı noktalara rehberli turlar sunar ."
12432,tr,"Aksi takdirde , oteller manzaralı noktalara rehberli turlar sunar ."

In [10]:
train_df = train_df.drop_duplicates().reset_index(drop=True)

In [11]:
print("Number of duplicate rows:", train_df.duplicated().sum())

Number of duplicate rows: 0

In [12]:
print("Dataset shape:", train_df.shape)

Dataset shape: (68980, 2)

#### Check dataset balancing

In [13]:
def check_df_balancing(df: pd.DataFrame, target: str) -> pd.DataFrame:
    return pd.concat(
        [
            df[target].value_counts(),
            df[target].value_counts(normalize=True) * 100,
        ],
        axis=1, keys=["Count", "Percentage"]
    )

In [14]:
check_df_balancing(train_df, target="labels")

        Count  Percentage
labels
ja       3500    5.073934
de       3499    5.072485
en       3499    5.072485
es       3498    5.071035
fr       3495    5.066686
zh       3491    5.060887
bg       3464    5.021745
tr       3464    5.021745
vi       3464    5.021745
hi       3464    5.021745
ar       3464    5.021745
th       3463    5.020296
el       3463    5.020296
ru       3463    5.020296
sw       3463    5.020296
ur       3456    5.010148
pt       3350    4.856480
it       3346    4.850681
nl       3340    4.841983
pl       3334    4.833285

#### Sample text data for inspection

show a representative sample of data texts to find out required preprocessing steps

In [15]:
def show_samples(df: pd.DataFrame, target: str, text_col: str, n: int = 5):
    for cls in df[target].unique():
        print(f"\nClass: {cls}")
        print("-" * 40)

        sample = df[df[target] == cls].sample(n=min(n, len(df[df[target] == cls])))

        for _, row in sample.iterrows():
            print(f"{row[target]} | {row[text_col]}\n")

In [16]:
show_samples(train_df, target="labels", text_col="text", n=5)

Class: pt
----------------------------------------
pt | Um homem está a cortar uma corda com uma espada.

pt | Olivia Colman ganha segundo Prémio BAFTA

pt | Futuros KLCI negociados mistos a meio do dia

pt | Os clientes surdos processam a Starbucks, dizem que são gozados

pt | Ataque suicida do Iémen mata 7 soldados: oficiais


Class: bg
----------------------------------------
bg | fda се позова на раздели 502 , 510 , 518 , 519 , 520,701 , 704 и 903 от федералния закон за храните , наркотиците и козметичните продукти ( 21 г . ) .

bg | точно като пролетен лук .

bg | основното пристанище , kamares , лежи на 5 км ( 3 км ) от столицата аполония , и сестра му град artemon ( и двете са наречени за брат и сестра бог и богиня на древната гръцка митология ) .

bg | прочетох нещо във вестника. да , днес прочетох нещо във вестника , за което говорят , или е било списание " парад " вчера и казаха , че знаеш кога е последният епизод и какво ще се случи , а те казват , че вътрешни хора казват : младши ще бъде ударен .

bg | и това ме направи , но аз не съм човек , който може да отиде на спа и да работи , просто ако нещо като


Class: zh
----------------------------------------
zh | 差评，盗版到不行，第二册直接没了20多页，然后重复了40多页

zh | 简直是老土 一般人很难撑住 买个m比加大还大 海淘还不好退货 只能送人了

zh | 牛仔衣属于偏薄的，春秋穿很合适。尺寸和国内的一样，袖子偏长。

zh | 干货太少，太过故事化，没有看到世界500强，大部分都在讲乡镇企业，还有作者的小聪明，很多内容都太偏太浅。（书名具有严重欺骗性）

zh | 右脚后内侧不跟脚，穿上第二天才发现，申请退货了，但是亚马逊的退货太麻烦了！还要打印单据，我到哪里去打，还要去买台打印机吗！


Class: th
----------------------------------------
th | ฉัน ไม่ได้ เห็น เลย ว่า เขา เล็ก ขนาด ไหน จนกว่า เขา จะ ตาย แล้ว

th | ฉัน รู้ ว่า มี ท่อ ส่ง ท่อ เข้าไป ใน เพนซิลเวเนีย ภาคใต้ และ มี กลุ่ม ใน เขต   bucks   ที่ กำลัง ต่อสู้ กับ มัน และ หนึ่ง ใน ผู้หญิง ที่ เป็น ผู้นำ กลุ่ม พูด ดี พวกเขา บอ กว่า พวกเขา จะ ไป ปั๊มน้ำมัน ผ่าน ที่นั่น แต่ก่อน นาน พวกเขา จะ สูบ กัมมันตภาพรังสี ผ่าน มัน

th | แม้ จะ มี การโต้เถียง ที่ น่าสนใจ ทั้งหมด ที่ เสนอ มา ใน ย่อหน้า ก่อนหน้านี้ มัน ก็ จะ งี่เง่า และ ไม่ ซื่อสัตย์ ที่จะ ยืนยัน ว่า

th | การ รื้อถอน ของ   wynn   ของ คุณสมบัติ ที่ มี อยู่ เริ่ม เป็น กระแส ที่ มากกว่า อื่นๆ อธิบาย   las   vegas   ใน ตอนท้าย ของ การ กำจัด ที่   20   ของ สรรพคุณ เก่า เพื่อ แลก กับ ศักยภาพ ของ ใหม่

th | นั่น มัน คือ ส่วน ที่ สนุก ที่ พยายาม จะ คิดออก ว่า คุณ ได้ อะไร มา เพื่อ พันธุ์ พวก มัน ด้วย ไม่ สามารถ ออก ไป ข้างนอก และ บอ กว่า โอเค พวกคุณ พันธุ์ ที่ คุณ รู้ ว่า


Class: ru
----------------------------------------
ru | Район Рейн-вэлли вокруг лиона - эпицентр французской кухни .

ru | Я знаю , уайт .

ru | Я говорю и делаю это ясно : если вы делаете постоянную практику торговли ударами с в или с кем-то еще , потому что вы не любите его лицо , то , как его уши держатся , как он ходит или говорит , или какого цвета пальто , которое он носил на войне , потом вы можете ролл свои кровати и уйти чем раньше , тем лучше .

ru | Ушел , чтобы допросить слуг .

ru | Но даже в тех случаях , когда они не пользуются преимуществами , многие люди могут принимать серьезные решения неправильно -- достаточно того , что мы должны сомневаться в патерналисты убеждениях , что люди должны делать то , что они хотят и


Class: pl
----------------------------------------
pl | Dziewczyna wskakuje na samochód.

pl | Napastnicy centrum handlowego Westgate spędzili cztery miesiące na planowaniu w Nairobi.

pl | "Izraelczyk" aresztowany w Jemenie Szpieg Mossadu

pl | Kobieta rozbija dwa jajka do szklanej miski.

pl | sheik doon salad ilmi powiedział, że ofiary cywilne wynikające z nocnych ataków moździerzowych i rakietowych zdarzają się każdego dnia.


Class: ur
----------------------------------------
ur | یہ یقینی طور پر کہ آپ کے دوستوں کی جانب سے رابطہ کیا جائے گا ۔

ur | تاہم ، مریخ کی اکثریت کو عطارد ، زہرہ ، اور عطارد کا تعین کرنا ضروری ہے ۔

ur | لیکن میں نے اس شخص کو کہہ دیا ہے کہ میں اس شخص سے ڈرتا ہوں اور ڈرتے رہو

ur | میں یاد نہیں کروں گا کہ روشنی کی روشنی کو بند کر دو ۔

ur | سٹیل اور اسٹیل کی وجہ سے ، جیسے کہ وانت سٹیل کے ساتھ ، سٹیل کے ذریعے ، سٹیل کے لئے ، سٹیل کے لئے ، سٹیل کے لئے ، سٹیل کے لئے ایک مختلف ٹیسٹ کا امتحان ہے . پوائنٹ ( logical analysis ) analysis ( graphical analysis ، logical analysis ) انجام دیا جاتا ہے ۔


Class: sw
----------------------------------------
sw | Miss tuppence is right , said sir james kimya kimya

sw | Pia ni mji mkuu wa sharon plain bahamian-growing area na kituo cha kiwanda cha diamond cha israel .

sw | Yeye mwezi mmoja katika shimo hilo , kisha humuadhibu majaji wenzake kwa ajili ya si faragha faragha na adhabu isiyo ya kawaida .

sw | Au long live ametakasika germany !

sw | Pili , gharama ya kudumisha mfanyakazi wa uga wa muda kamili katika tovuti anaendesha juu , ili evaluators na kwa uchunguzi mfupi au wafanyakazi wa uga wa ya au wote wawili .


Class: tr
----------------------------------------
tr | Karayipler ' de en vahşi olmayabilir ama fwi karnavalı en uzun , 24 saat kadar .

tr | Ordu ' nun kahramanlar daha çok var .

tr | Quaaludes üzerine .

tr | Ve bunu rastgele bir şekilde yapıyorlar . Eğer gerçekten rastgele olursa , herkesin beş yıl içinde test emin değilim .

tr | Çok sayıda araştırmacı , alkol sorunlarına hitap etmemiz gerektiğini bildiği için bu müdahaleler klinik ayarlara taşımak için acele ettiğini kaydetti .


Class: es
----------------------------------------
es | Es tal como se muestra en la foto. Se coloca mediante una pinza consiguiendo un gran agarre. No molesta, aunque pesa un poquito (son extensiones muy largas y densas). El resultado es bastante natural. A pesar de tener un precio bajo, el brillo del pelo no resulta artificial. Se enreda un poco al llevarla puesta, pero puede peinarse sin problema. Por la forma en la que se encuentra insertado el pelo en la pinza, si se intenta hacer una trenza el inicio queda raro... Pero como cola es perfecta. Cambio de look en un segundo.

es | Parece más robusto de lo que en realidad es. Lo compré para separación de ambientes pero es difícil que se mantenga de pie dado que tiene poca estabilidad.

es | La pulsera en si es muy original,le viene bien de tamaño,parece un poco mas pequeña que en las fotos,pero cumple su funcion,el envio bastante bien,en fin buena nota para un producto que encanto a una fan de Potter.

es | Muy bien el.tiempo de entrega pero la calidad es muy mala parece como tema de pañal de be be.

es | Al principio estuve muy contenta con mi cargador multiple, pero en cuanto pasó solo un mes empezó a dejar de cargar. Siempre había problemas con el cable. Hasta que a los dos meses ya ha dejado de funcionar. NADA RECOMENDABLE. NO LO COMPRES


Class: ar
----------------------------------------
ar | 2 ثانية للمدينة السكنية .

ar | ويتطلب ذلك انشاء قاعدة مورد ومواد شراء .

ar | كان هناك ذلك الوقت عندما كان العم ( موراي ) قد امسك به في الجدول , صنع قوارب ورقية .

ar | لقد وضع يده في جيبه .

ar | كان المصري ( 6712 هوليوود بولفارد ) اول قصر سينمائي في هوليوود , بناها graumann في عام 1922 بعد اكتشاف قبر الملك توت .


Class: it
----------------------------------------
it | Dotson, 21 anni, è stato arrestato e accusato il 21 luglio dopo aver riferito alle autorità di aver sparato a Dennehy dopo che Dennehy aveva tentato di sparargli.

it | ISAF: 4 truppe della coalizione uccise in un attacco che coinvolgeva la polizia afghana

it | Coloro che hanno rifiutato le tessere mediche hanno esortato a contattare l'HSE

it | I ribelli siriani lasciano Homs assediata

it | Credo che con gli imprenditori non si capisca il punto.


Class: hi
----------------------------------------
hi | क ् या अधिक है , व ् हाइट-ब ् लैक विवाह दर दूसरे , nonblack दौड ़ के साथ सफेद intermarriage की दरों के पीछे काफी है .

hi | नाम एनएओ के अंतर ् गत कम विस ् तृत मॉडल बेचे जाते हैं .

hi | उन ् होंने संकेत दिया कि 2001 से अधिक लोगों को 183,000 से अधिक लोग दिखाए गए थे .

hi | तो नमस ् कार मैरी

hi | हाँ और मैं इसका मतलब है कि अखबार सिर ् फ शैक ् षणिक तंत ् र के बारे में इस सामग ् री से भरा है , वे अपने मानकों को बदल रहे हैं और यह कि और यह सब कुछ बेहतर बनाने जा रहा है


Class: de
----------------------------------------
de | Dvd kam wie immer super pünktlich an, der Film ist spitze

de | Seehr schlechte Verarbeitung. Hab umgehend einen Rücksendeantrag gestellt.

de | Leider ist die Verarbeitung nicht so gut wie ich es von den grossen Zangen gewohnt bin.

de | Super Schnelle Lieferung. Ausgepackt an den Kobold VK 131 angesteckt und los ging es. Wirklich Klasse Ergebnis auf Parkett und Fliesen. Wirklich sehr weiter zu Empfehlen.

de | ich habe keine lust, öl zum teuren preis bei der tankstelle zu kaufen. Hier zahle ich im Verhältnis einen Spottpreis für so ein Qualitätsprodukt


Class: el
----------------------------------------
el | Ο τελικός κανόνας εκδόθηκε σύμφωνα με την αρχή του ομοσπονδιακού νόμου για τα τρόφιμα , τα ναρκωτικά και τα καλλυντικά και τον νόμο για τη δημόσια υγεία , όπως κωδικοποιημένη στο 21 u.s.c.

el | Το 1986 η Πορτογαλία προσχώρησε στην ευρωπαϊκή οικονομική κοα ; Έunity ( τώρα η Ευρωπαϊκή Ένωση ή η ΕΕ ) .

el | Κάνε ακριβώς το σωστό και

el | Υπάρχουν κομμάτια του ματίς , του magritte , του μιρ ? ? , και του χόκνεϊ .

el | Ναι είναι πολύ ακριβά εννοώ ακόμα και


Class: nl
----------------------------------------
nl | Een Victory Liner bus is wit met rode en gouden strepen.

nl | Een man is luidsprekeronderdelen aan het monteren.

nl | De VS biedt 10 miljoen dollar aan voor de Pakistaanse militante...

nl | China stelt Bo Xilai testdatum vast

nl | Het hangt ervan af hoe je extreem definieert.


Class: fr
----------------------------------------
fr | Jusqu’ici il est l’un des rares médicaments à me faire passer d’assez bonne nuit, car je me réveille très, très, très mais très souvent les nuits dû au stresse de mon entreprise ... mieux que novanuit en tout cas.

fr | Livre solide, très bien fait pour que les petits découvre ce qui se passe dans les couches.

fr | Conforme à la photo

fr | Support portable joli et le couleur magnifique. Bonne achat et satisfait, solide et flexible

fr | Métal Plus fin que ce que je pensais, mais supporte quand même le poids de mon pot de fleur. J'ai préféré utiliser mes propres chevilles car celles fournies semblaient être fragiles.


Class: vi
----------------------------------------
vi | Anh đoán sai rồi , nói với luật sư đi .

vi | La cetellana và paseo de recoletos là continuations phía bắc của đại lộ prado của cái .

vi | Avenger mua sắm , trong khi không nhận diện chính mình là avenger mua sắm -- Điều này sẽ có nghĩa là thay đổi vào túi quần áo và áo choàng trong phòng khách hàng -- Thông báo cho nhân viên của British Airways rằng người dùng mua sắm là người tiêu dùng hàng đầu của nước mỹ . Người ủng hộ ( đây là một lời nói dối , nhưng cô ấy là người anh , vậy cô ấy biết gì ? ) ) ) ) ) ) ) ) ) ) )

vi | Sự lãnh đạo là về việc thông minh , chăm chỉ , và vẽ những công việc tốt nhất từ một đội .

vi | Vâng , dễ dàng hơn


Class: en
----------------------------------------
en | Extremely slow read. Couldn’t make it through the book.

en | Good quality, feels much better when shifting than previous plastic knob.

en | This came noticeably second hand, already opened and taped over. Very disappointed.

en | This is my second microcurrent product. I purchased a Nuface years ago, it broke and decided to give this product a try, because of the reviews. It pulls wayyyy more current than the Nuface! This product was also less than they Nuface by hundreds! Very glad I purchased. It’s only been a week- so I can’t tell yet if it’s “working” but the current I feel gives me hope!

en | This binder is big, perhaps too big to fit insides a backpack.


Class: ja
----------------------------------------
ja | これまで2台購入しています。 ページを抑える力も問題ないです。 比較的大きな、鈍器のような本も支えてくれます。

ja | 今飲んでいる茎茶に代わるものを探すため色々な産地のお茶を飲んでいるところです。

ja | 一枚の革かと思っていたが、裏に合皮のものだった。合皮部分があるので耐久性が微妙です。

ja | 1ポートだけですが、充電が早くて本当にびっくりしました。この品質でこの価格なら大満足です。

ja | 汎用ハーネスセットと純正変換セットの組み合わせで届きました。 面倒ですが使用は出来るので返金・返品などの対応は必要有りませんが、説明写真の商品では有りません。 配線がゴチャゴチャしてしまうので取り扱いし難いです。 私は加工して使用することが出来ましたが加工前提ならば他のセットを購入するか、返品返金などの対応をお勧めします。

**Cleaning and Preprocessing are:**

- Lowercase
- Removing URLs
- Removing Mentions
- Handling Hashtags
- Removing extra spaces

### Cleaning and Preprocessing

In [17]:
!pip install -q emoji

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 16.2 MB/s eta 0:00:00

In [18]:
import re
import emoji

def clean_text(text):
    # Lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r"http[s]?://\S+|www\.\S+", "", text)

    # Remove mentions
    text = re.sub(r"@\w+", "", text)

    # handle hashtags
    text = re.sub(r"#(\w+)", r"\1", text)

    # Remove emoji
    text = emoji.replace_emoji(text, replace="")

    # Remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [19]:
X_train, y_train = train_df["text"], train_df["labels"]
X_val, y_val = val_df["text"], val_df["labels"]
X_test, y_test = test_df["text"], test_df["labels"]

### Model Pipeline

In [20]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC

pipeline = Pipeline([
    ("vectorizing", TfidfVectorizer(
        preprocessor=clean_text,
    )),
    ("model", LinearSVC(random_state=42))
])

In [21]:
param_grid = {
    "vectorizing__analyzer": ["word", "char_wb"],
    "vectorizing__ngram_range": [(2, 3), (2, 4), (3, 5)],
    "vectorizing__max_features": [3000, 5000, 10000, None],
    "model__C": [0.01, 0.1, 1, 3, 5, 10, 20],
}

In [22]:
from sklearn.model_selection import RandomizedSearchCV, StratifiedKFold

cv = StratifiedKFold(
    n_splits=3,
    shuffle=True,
    random_state=42
)

random_search = RandomizedSearchCV(
    pipeline,
    param_distributions=param_grid,
    n_iter=10,
    cv=cv,
    scoring="f1_macro",
    n_jobs=-1,
    verbose=1,
    random_state=42
)

In [23]:
random_search.fit(X_train, y_train)

Fitting 3 folds for each of 10 candidates, totalling 30 fits

RandomizedSearchCV(cv=StratifiedKFold(n_splits=3, random_state=42, shuffle=True),
                   estimator=Pipeline(steps=[('vectorizing',
                                              TfidfVectorizer(preprocessor=<function clean_text at 0x7f6af1d45620>)),
                                             ('model',
                                              LinearSVC(random_state=42))]),
                   n_jobs=-1,
                   param_distributions={'model__C': [0.01, 0.1, 1, 3, 5, 10,
                                                     20],
                                        'vectorizing__analyzer': ['word',
                                                                  'char_wb'],
                                        'vectorizing__max_features': [3000,
                                                                      5000,
                                                                      10000,
                                                                      None],
                                        'vectorizing__ngram_range': [(2, 3),
                                                                     (2, 4),
                                                                     (3, 5)]},
                   random_state=42, scoring='f1_macro', verbose=1)

### Best Model

In [24]:
best_model = random_search.best_estimator_

print("Best Params:")
print(random_search.best_params_)

Best Params:
{'vectorizing__ngram_range': (2, 4), 'vectorizing__max_features': None, 'vectorizing__analyzer': 'char_wb', 'model__C': 10}

### Evaluation

In [25]:
from sklearn.metrics import classification_report, f1_score, accuracy_score


y_val_pred = best_model.predict(X_val)

print("Val Accuracy:", accuracy_score(y_val, y_val_pred))
print("Val F1 Macro:", f1_score(y_val, y_val_pred, average="macro"))

print("\nClassification Report:\n")
print(classification_report(y_val, y_val_pred))

Val Accuracy: 0.9954
Val F1 Macro: 0.9953929511864207

Classification Report:

              precision    recall  f1-score   support

          ar       1.00      0.99      1.00       500
          bg       1.00      1.00      1.00       500
          de       1.00      1.00      1.00       500
          el       1.00      1.00      1.00       500
          en       0.99      1.00      1.00       500
          es       1.00      1.00      1.00       500
          fr       1.00      1.00      1.00       500
          hi       1.00      0.95      0.98       500
          it       1.00      1.00      1.00       500
          ja       1.00      1.00      1.00       500
          nl       0.98      1.00      0.99       500
          pl       1.00      1.00      1.00       500
          pt       1.00      1.00      1.00       500
          ru       1.00      1.00      1.00       500
          sw       0.95      1.00      0.98       500
          th       1.00      1.00      1.00       500
          tr       0.99      1.00      1.00       500
          ur       1.00      0.97      0.98       500
          vi       1.00      1.00      1.00       500
          zh       1.00      1.00      1.00       500

    accuracy                           1.00     10000
   macro avg       1.00      1.00      1.00     10000
weighted avg       1.00      1.00      1.00     10000

In [26]:
y_test_pred = best_model.predict(X_test)

print("TEST Accuracy:", accuracy_score(y_test, y_test_pred))
print("TEST F1 Macro:", f1_score(y_test, y_test_pred, average="macro"))

TEST Accuracy: 0.995
TEST F1 Macro: 0.9950108361151926

---

### Save Model

In [31]:
import joblib

joblib.dump(best_model, "svc_language_detector_v2.pkl")

['svc_language_detector_v2.pkl']

### Load and Predict

In [32]:
model = joblib.load("svc_language_detector_v2.pkl")

In [33]:
text = ["كيف الحال ؟"]
model.predict(text)

array(['ar'], dtype=object)

---